name: Lint and Format Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-and-format:
    name: Run ESLint and Prettier Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run format:check

      - name: Run ESLint check
        run: npm run lint
